name: Rdio-Scanner

on: 
  release: 
    types: [published]

jobs:
  build:
    name: Build rdio-scanner
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v5.0.0
    - name: Setup Go environment
      uses: actions/setup-go@v6.0.0
    - name: Setup TeXLive Action 2
      uses: TeX-Live/setup-texlive-action@v3.4.2
    - name: Install other build requirements
      run: |
        sudo apt update
        sudo apt install -y build-essential texlive-extra-utils texlive-latex-extra pandoc podman unzip
    - name: Build with make
      run: make
    - name: Upload build artifacts (zip files)
      uses: actions/upload-artifact@v4
      with:
        name: rdio-scanner-zips
        path: ./dist/*.zip
    - name: Upload release assets to GitHub
      uses: softprops/action-gh-release@v2
      with:
        files: ./dist/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                
                
