name: Rdio-Scanner

on: 
  release:
  workflow_dispatch:

jobs:
  build:
    name: Bulds rdio-scanner
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v5.0.0
    - name: Setup Go environment
      uses: actions/setup-go@v6.0.0
    - name: Setup TeX Live
      run: |
        sudo apt update
        sudo apt install -y texlive-full
    - name: Setup pandoc
      run: |
        sudo apt update
        sudo apt install -y pandoc pandoc-pdf
    - name: Install Podman
      run: |
        sudo apt update
        sudo apt install -y podman unzip
    - name: Build with make
      run: |
        cd rdio-scanner
        make
    - name: Upload build artifacts (zip files)
      uses: actions/upload-artifact@v4
      with:
        name: rdio-scanner-zips
        path: ./rdio-scanner/dist/*.zip
    - name: Upload release assets to GitHub
      uses: softprops/action-gh-release@v2
      with:
        files: ./rdio-scanner/dist/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                
                
